(ns frontend.views
  (:require [re-frame.core :as rf]
            [frontend.subs :as subs]
            [antizer.reagent :as ant]
            [frontend.intro.views :as intro-views]
            [frontend.survey.views :as survey-views]
            [frontend.annotator.views :as annotator-views]))

(defn footer []
  [ant/row
   [:hr]
   [:p.footer
    "Provided by the HCC Group @ FU Berlin."
    [:br]
    "If you have any questions please contact us."
    [:br]
    "  If you can not finish this hit due to errors, please contact us via the mturk interface."]])

(defn tutorial []
  [ant/row
   [:main.container
    [:div.row
     [:div.col
      [:h1 "Interactive Concept Annotation"]]]
    [:div.row
     [:div.col
      [:h2 "Task"]
      [:p "In this task, you will annotate concepts within idea texts."]
      [:h3 "How does the software look like?"]
      [:div.image-container
       [:img.image.img-thumbnail {:src "/images/annotator-tutorial.gif"}]]
      [:p "In the gif you can see a header and two panels. In the top left you can see the task description and
                    the challenge that the ideas were generated for.
                In the top right, you see your current progress in the idea annotation
                In the left panel ('Idea Text'), you will get the idea text, that has to be annotated.
                In the right panel ('Validation') you will see a list of possible concepts for the currently
                active word (marked in yellow on the left). This will change each time you annotate a concept."]
      [:h3 "What do I have to do?"]
      [:p "In order to annotate the ideas, please go through all the highlighted terms on the left and
                select all definitions that might fit in the list on the right."]
      [:p "For each term, you can select multiple definitions. Please select all definitions that fit, how
                the word is used in the idea text. The gif shows this for one example idea."]
      [:h3 "Where do the ideas come from?"]
      [:p "The ideas were generated by mechanical turk workers in HITs we previously published."]]]
    [:div.row
     [:div.col
      [:p "This is a prototype: If you run into trouble, contact us (screenshot of
                    the error would be much appreciated) and we will
                    resolve the issues."]]]
    [ant/button {:type "primary"}
     [:a {:href "#/annotator"} "Go to annotator"]]]])

(defn pages [page-name]
  (case page-name
    :home [intro-views/intro]
    :tutorial [tutorial]
    :annotator [annotator-views/annotator-main]
    :thank-you [survey-views/thank-you]
    [intro-views/intro]))

(defn annotation-app
  []
  (let [active-page @(rf/subscribe [::subs/active-page])]
    [ant/layout
     [ant/layout-content
      [pages active-page]
      [footer]
      ]]))